language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh 
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --prepend channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n ci_env python=3.7 shapely rtree fiona
  - source activate ci_env
script:
# Test SherBend
# -------------
# Remove file from previous execution
  - rm -f ./data/test_sherbend_out.gpkg
# Test for Sherbend
# Create the new file
  - python sherbend.py -d 2.0 ./data/test_sherbend_in.gpkg ./data/test_sherbend_out.gpkg
# Validate that the content is equal to the standard file
  - python test_sherbend.py ./data/test_sherbend_out.gpkg ./data/test_sherbend_out_standard.gpkg
#
# Test ChordalAxis
# ----------------
# Delete layer in the geopackage using GDAL (ogrinfo)
  - ogrinfo -sql "DROP TABLE Skeleton" ./data/test_chordal_axis
  - ogrinfo -sql "DROP TABLE SkeletonCorrect" ./data/test_chordal_axis
# Create the Chordal Axis
- chordal_axis -t Triangles -s Skeleton ./data/test_chordal_axis
- chordal_axis -t Triangles -s SkeletonCorrect -c ./data/test_chordal_axis
  

