dist: focal
#
language: python
#
python:
  - "3.8"
#
install:  
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r 
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create --name qgis_316 python=3.8 qgis=3.16.3 --channel conda-forge
#
script:
# Metric unittest
#
# Activate QGIS conda environment
  - conda activate qgis_316
#
# Need to execute the metric with QT_QPA_PLATFORM=offscreen otherwise QGIS does not start
# Execute unittest for reduce bend 
  - QT_QPA_PLATFORM=offscreen python -m unittest reduce_bend_unittest.py
#  
# Execute unittest for chordal axis 
  - QT_QPA_PLATFORM=offscreen python -m unittest chordal_axis_unittest.py

